export const ERROR = 'ERROR'

export const GET_FEEDS = 'GET_FEEDS'
export const FEEDS_UPDATED = 'FEEDS_UPDATED'
export const FEEDS_RETURNED = 'FEEDS_RETURNED'

export const GET_PRICES = 'GET_PRICES'
export const PRICES_UPDATED = 'PRICES_UPDATED'
export const PRICES_RETURNED = 'PRICES_RETURNED'
